# fmt: off
questions = [
    "An artist is creating a large mosaic using square tiles. The mosaic is designed to be a square itself and to contain exactly 3 times as many blue tiles as red tiles. If the artist has only 57 red tiles, how many tiles in total will be used to construct the complete mosaic?",
    "A farmer is filling baskets with apples for a local market. He has 120 apples and wants to distribute them evenly among his baskets. If he decides to keep 15 apples for his family and each basket can hold no more than 7 apples, what is the minimum number of baskets he needs to use for the market?",
    "A garden has rectangular plots arranged in such a way that each plot shares sides with exactly two other plots, forming a straight line. There are 5 plots in total. Each of the middle plots has an area of 24 square meters, and the width of the plots is 4 meters. The width remains constant for all plots. The first plot in the line is twice as long as a middle plot, and the last plot is half as long as a middle plot. What is the total area of all the plots combined?",
    "A farmer's market sells apples in two types of mixed bags: Type A contains 4 red apples and 6 green apples, and Type B contains 8 red apples and 4 green apples. A customer purchases one bag of each type. What is the probability that a randomly picked apple from the collection of apples in both bags will be a green apple? Express your answer as a decimal rounded to the nearest hundredth.",
    "A gardener is planting flowers in a pattern: two red flowers followed by one yellow flower. If the gardener wants to maintain this pattern and has 35 spaces in a row to fill, how many red flowers will the gardener plant?",
    "Jason is training for a marathon and runs a certain distance each day. On Monday, he runs 5 miles. Each day after, he increases his distance by 10%. If Jason continues this pattern, how many miles will he run on Friday?",
    "In a triangular garden bed, there are 16 plants along each side. Each plant requires a circular space with a radius of 0.5 meters to grow properly. Assuming plants are placed exactly next to each other, without overlapping, and maintaining a straight line from one corner of the triangular bed to the other, how much linear meter space is used by plants along one side of the garden bed?",
    "Dr. Wilson is planting a geometric garden with flowers arranged in concentric rings around a central fountain. Each outer ring has 6 more flowers than the inner one, forming a hexagonal pattern. The innermost ring has 6 flowers. If Dr. Wilson plants enough flowers to form 15 rings, including the innermost ring, what is the total number of flowers needed for the garden?",
    "A small library is reorganizing its collection. They have a total of 120 books to distribute equally among 5 shelves. The top shelf can only bear a load of books equal to half the weight supported by the bottom shelf. If the top shelf holds 15 pounds of books and the other shelves can each hold twice as much weight, how many pounds can the bottom shelf hold?",
    "A recipe for a batch of cookies requires 3 cups of flour, 2 cups of sugar, and 1 cup of chocolate chips. If Max wants to make a triple batch but only has 4 cups of sugar, how many more cups of sugar does he need?",
    "A pet store owner is making custom birdhouses. Each birdhouse requires 0.75 liters of wood varnish for the exterior. If the owner has a 10-liter can of wood varnish, how many birdhouses can he finish before needing more varnish?",
    "A farm has chickens and cows. If there are a total of 30 heads and 88 legs, how many cows are on the farm?",
    "A local library is organizing a book fair where they sell used books to raise funds for new acquisitions. They sell 120 children's books for $2 each, 75 novels for $3 each, and twice as many magazines as novels at $1.50 each. They also sell bookmarks at $0.50 each. If they sell as many bookmarks as the total number of books and magazines sold, how much money does the library raise in total?",
    "A local farmer is preparing mixed fruit baskets using apples, oranges, and bananas. Each basket must contain 3 apples, 5 oranges, and 2 bananas. The apples are sold at $0.50 each, oranges at $0.30 each, and bananas at $0.25 each. If the farmer prepares 120 baskets for a local market and sells each basket for $5.00, how much profit will the farmer make after selling all the baskets?",
    "Maria has 24 apples and wants to divide them equally among her 6 friends. If each friend also gives 2 apples to their teacher, how many apples will each friend have left?",
    "Lila is planning a garden and wants to plant three types of flowers: daisies, tulips, and roses. She wants twice as many daisies as tulips and three times as many tulips as roses. If she plants a total of 60 flowers, how many roses is she planning to plant?",
    "A garden has three types of flowering plants. The first type has 12 flowers each, the second type has 8 flowers each, and the third type has 15 flowers each. If there are twice as many first-type plants as second-type plants and half as many third-type plants as first-type plants, and the garden has a total of 16 second-type plants, how many flowers are there in the garden?",
    "In a certain board game, transferring from one square to another costs as many coins as the number of the square you're landing on. The first square is number 1, the second square is number 2, and so on in numerical order. If a player transfers from square 5 to square 9 in one move, then to square 14 in the next, and finally to square 20, how many coins have they spent in total?",
    "A landscaping company plants trees in two parks. In Park A, they plant 5 rows of trees with 6 trees in each row. Park B is smaller, so they plant 3 rows with 7 trees in each row. However, 4 trees in Park B don't survive and must be removed. How many trees are left in total after the removals?",
    "Dr. Euler is planning a math tournament and decides to arrange the participants in groups. Each group must have the same number of participants to ensure fairness. If Dr. Euler can choose to arrange them in groups of either 4, 5, or 6, and he knows there are fewer than 100 participants, what is the largest number of participants that he can have to ensure he has no one left over no matter how he arranges the groups?",
    "A farmer has allocated a section of his land to grow pumpkins for the Halloween season. He plants 8 rows of pumpkin plants, with each row containing 15 pumpkin plants. Each pumpkin plant yields an average of 3 pumpkins. After harvest, the farmer sells 20% of the pumpkins to a local market and the rest at his farm stand. If each pumpkin sells for $4, how much total revenue does the farmer make from pumpkin sales?",
    "A triangular park ABC has trees planted along its edges. The number of trees planted on edge AB is equal to the length of edge BC, the number of trees on edge BC is equal to the length of edge CA, and the number of trees on edge CA is equal to the length of edge AB. If the lengths of edges AB, BC, and CA (in meters) form a geometric progression whose common ratio is 2, and the total number of trees planted is 77, find the length of edge AB.",
    "A group of friends are collecting cans for recycling. Maya collected twice as many cans as Liam. Liam collected 15 cans. If Zoe collected 5 more cans than Maya and the group wants to divide the total number of cans equally between 4 charities, how many cans will each charity receive?",
    "In a science competition, each team needs to build a model rocket. There are 6 teams and each team requires 1 set of materials. A set of materials includes the body tube, the engine, and the parachute. The body tube costs $12.50 each, the engine costs $18.75 each, and the parachute costs $6.25 each. After purchasing the materials for all teams, the total cost was $225. How much did the materials for one team's rocket cost?",
    "Emily has a small vegetable garden where she grows tomatoes, carrots, and cucumbers. She has twice as many tomato plants as cucumber plants, and 5 fewer carrot plants than tomato plants. If Emily has 4 cucumber plants, how many vegetable plants does she have in total?",
    "In a small village, the local tailor makes coats and trousers. He uses 3 yards of fabric for a coat and 2 yards for a pair of trousers. He has received an order for a theater production that requires twice as many trousers as coats, and the production has asked for 4 coats. If fabric costs $15 per yard, how much will the production spend on fabric for this order?",
    "A town's population grows at a constant rate. If the town's population was 5,000 in the year 2010 and 8,000 in the year 2020, what will the town's population be in the year 2025 if the growth trend continues?",
    "A math teacher is organizing a quiz competition and has decided to give out pencils as prizes. Every participant will receive 2 pencils, but those who score above 80% will receive an additional 3 pencils as a bonus. If there are 30 students in the class and 1/5 of the students score above 80%, how many pencils does the teacher need to have for the competition?",
    "A rectangular garden is enclosed by 120 meters of fencing. If the length of the garden is three times its width, what is the area of the garden in square meters?",
    "A garden measuring 10 meters by 15 meters is to be covered by square tiles. Each tile has a side length of 25 centimeters. If the price of each tile is $3 and the cost of labor per square meter for laying the tiles is $8, what is the total cost of tiling the garden?",
]
# questions += questions #60
# questions.append(questions[0])#61 likely to fail
answers = [
    228,
    15,
    132,
    0.45,
    24,
    7.3205,
    16,
    720,
    30,
    2,
    13,
    14,
    862.5,
    180,
    2,
    6,
    752,
    43,
    47,
    60,
    1440,
    11,
    20,
    37.5,
    15,
    420,
    9500,
    78,
    675,
    8400,
]
# fmt: on
